port: 8084
starttime: "2023-01-01"
machineid: 1
log:
  level: "info"
  filename: "logs/bluebell.log"
  maxsize: 10
  maxbackups: 5
  maxage: 30
  console: true
redis:
  host: "redis"       # Docker Compose 服务名
  port: 6379
  password: ""
  db: 0
  poolsize: 10
mysql:
  host: "mysql"       # Docker Compose 服务名
  port: 3306
  user: "root"
  password: "123456"
  dbname: "bluebell"
  maxopenconns: 20
  maxidleconns: 10
